gem 'pacer', :path => '~/xn/pacer'
gem 'pacer-neo4j', :path => '~/xn/pacer-neo4j'
gem 'pacer-dex', :path => '../pacer-dex'
gem 'pacer-orient', :path => '../pacer-orient'
gem 'nokogiri'
gem 'awesome_print'
